# One of the main reasons for choosing YAML over JSON is being able to use comments

# First Feed
-
  url: http://example.com
  parser: example_list
  destination: s3://www-example-com/index.html

# Second Feed
-
  url: http://www.filltext.com/?rows=10&fname={firstName}&lname={lastName}&tel={phone|format}&address={streetAddress}&city={city}&state={usState|abbr}&zip={zip}
  parser: example_list
  destination: s3://www-example-com/index.html

# Third Feed
-
  url: http://beta.json-generator.com/api/json/get/FrBbyBY
  parser: example_list
  destination: s3://www-example-com/index.html

# Forth Feed
-
  url: http://www.json-generator.com/api/json/get/bSCtXmzOEO?indent=0
  parser: example_list
  destination: s3://www-example-com/index.html
